# -*- coding: utf-8 -*-
"""django-confit documentation build configuration file."""
import os
import re

from django.conf import settings


# Minimal Django settings. Required to use sphinx.ext.autodoc, because
# django-confit depends on Django...
settings.configure()


doc_dir = os.path.dirname(os.path.abspath(__file__))
project_dir = os.path.dirname(doc_dir)
version_filename = os.path.join(project_dir, 'VERSION')


# -- General configuration ----------------------------------------------------

# Sphinx extension module names.
extensions = ['sphinx.ext.autodoc',
              'sphinx.ext.autosummary',
              'sphinx.ext.doctest',
              'sphinx.ext.coverage',
              'sphinx.ext.intersphinx']

# Add any paths that contain templates here, relative to this directory.
templates_path = ['_templates']

# The suffix of source filenames.
source_suffix = '.txt'

# The master toctree document.
master_doc = 'index'

# General information about the project.
project = u'django-confit'
project_slug = re.sub(r'([\W_.-]+)', u'-', project)
copyright = u'2014 - Benoît Bryon'
author = u'Benoît Bryon'
author_slug = re.sub(r'([\W_.-]+)', u'-', author)

# The version info for the project you're documenting, acts as replacement for
# |version| and |release|, also used in various other places throughout the
# built documents.
configuration_dir = os.path.dirname(__file__)
documentation_dir = configuration_dir
version_file = os.path.normpath(os.path.join(
    documentation_dir,
    '../VERSION'))

# The full version, including alpha/beta/rc tags.
release = open(version_file).read().strip()
# The short X.Y version.
version = '.'.join(release.split('.')[0:1])

# The language for content autogenerated by Sphinx. Refer to documentation
# for a list of supported languages.
language = 'en'

linkcheck_timeout = 10


# -- Options for HTML output --------------------------------------------------

# Custom sidebar templates, maps document names to template names.
html_sidebars = {
    '**': ['globaltoc.html',
           'relations.html',
           'sourcelink.html',
           'searchbox.html'],
}

# Output file base name for HTML help builder.
htmlhelp_basename = u'{project}doc'.format(project=project_slug)


# -- Options for sphinx.ext.intersphinx ---------------------------------------

intersphinx_mapping = {
    'python': (
        'http://docs.python.org/2.7',
        None),
    'django': (
        'http://docs.djangoproject.com/en/1.9/',
        'http://docs.djangoproject.com/en/1.9/_objects/'),
    'colander': (
        'http://docs.pylonsproject.org/projects/colander/en/latest/',
        None),
}

# -- Options for LaTeX output -------------------------------------------------

# Grouping the document tree into LaTeX files. List of tuples ``(source start
# file, target name, title, author, documentclass [howto/manual])``.
latex_documents = [
    ('index',
     u'{project}.tex'.format(project=project_slug),
     u'{project} Documentation'.format(project=project),
     author,
     'manual'),
]


# -- Options for manual page output -------------------------------------------

# One entry per manual page. List of tuples
# (source start file, name, description, authors, manual section).
man_pages = [
    ('index',
     project,
     u'{project} Documentation'.format(project=project),
     [author],
     1)
]


# -- Options for Texinfo output -----------------------------------------------

# Grouping the document tree into Texinfo files. List of tuples
# (source start file, target name, title, author,
#  dir menu entry, description, category)
texinfo_documents = [
    ('index',
     project_slug,
     u'{project} Documentation'.format(project=project),
     author,
     project,
     'One line description of project.',
     'Miscellaneous'),
]
